# Generated by Django 4.2.18 on 2025-01-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roman_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historie',
            name='date',
            field=models.IntegerField(default=1000),
        ),
    ]
