# Generated by Django 4.2.18 on 2025-02-01 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roman_map', '0002_historie_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('coordinates', models.CharField(max_length=100)),
                ('historie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='roman_map.historie')),
            ],
        ),
    ]
