# Generated by Django 4.2.18 on 2025-02-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roman_map', '0003_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historie',
            name='coordinates',
        ),
        migrations.AlterField(
            model_name='historie',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='historie/'),
        ),
    ]
