# Generated by Django 4.2.18 on 2025-02-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roman_map', '0008_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='historie',
            name='coordinates',
            field=models.TextField(blank=True),
        ),
    ]
