# Generated by Django 4.2.18 on 2025-02-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roman_map', '0009_historie_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
