# Generated by Django 4.2.18 on 2025-02-05 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roman_map', '0010_alter_answer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompolygon',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='point',
            name='historie',
        ),
        migrations.DeleteModel(
            name='CustomPoint',
        ),
        migrations.DeleteModel(
            name='CustomPolygon',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
