# Generated by Django 4.2.18 on 2025-02-23 08:38

from django.db import migrations, models
import roman_map.models


class Migration(migrations.Migration):

    dependencies = [
        ('roman_map', '0014_alter_question_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=0, validators=[roman_map.models.Question.validate_positiv_number]),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='total_score',
            field=models.PositiveIntegerField(default=0, validators=[roman_map.models.UserScore.validate_positiv_number]),
        ),
    ]
