# Generated by Django 4.2.18 on 2025-03-01 11:06

from django.db import migrations, models
import roman_map.models


class Migration(migrations.Migration):

    dependencies = [
        ('roman_map', '0015_alter_question_points_alter_userscore_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='points_awarded',
            field=models.PositiveIntegerField(default=0, validators=[roman_map.models.UserAnswer.validate_positiv_number]),
        ),
    ]
